# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30)),
                ('business_descrpition', models.TextField()),
                ('user', models.CharField(max_length=30)),
                ('neighbourood', models.CharField(max_length=30)),
                ('business_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighnourhood_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('house_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('identification_card', models.IntegerField(default=0)),
                ('neighbourood', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField(default=0)),
            ],
        ),
    ]
