# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-02-24 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugoyawatch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Neighbourood',
            new_name='Neighbourhood',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='neighbourood',
            new_name='neighborhood',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='neighnourhood_name',
            new_name='neighborhood_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighbourood',
            new_name='neighborhood',
        ),
    ]
